---
language: python
python: 3.7.4

before_install:
- sudo apt-get update -qq
- openssl aes-256-cbc -K $encrypted_1a9d6c8ad656_key -iv $encrypted_1a9d6c8ad656_iv -in ansible/.secret.enc -out ansible/.secret -d

install:
- pip install ansible
- printf '[defaults] roles_path = ../' > ansible.cfg

script:
- cd ansible
- ansible-playbook -v -i inventories/scaleway.yml 10_configure.yml --syntax-check
...