---
language: python
python: "3.7.4"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "printf '[defaults]\nroles_path = ../' > ansible/ansible.cfg"

script:
  # We'll add some commands to test the role here.
  # Check the role/playbook's syntax.
  - cd ansible
  - ansible-playbook -v -i inventories/scaleway.yml 10_configure.yml --syntax-check