---

- hosts: k3s
  remote_user: root
  become: True
  roles:
    - role: ssh_setup
      tags:
        - ssh_setup
    - role: sudoers
      tags:
        - sudoers

- hosts: k3s
  become: True
  roles:
    - role: base_role
      tags:
        - base_role
    - role: chrony
      tags:
        - chrony
    - role: fail2ban
      tags:
        - fail2ban
    - role: docker-engine
      tags:
        - docker-engine
    - role: kubectl
      tags:
        - kubectl

    - role: minikube
      tags:
        - minikube

...