---

- name: Install EPEL repository.
  yum:
    name: epel-release
    state: present

- name: Disable SELinux.
  selinux:
    state: disabled

- name: Disable firewalld.
  service:
    name: firewalld
    state: stopped
    enabled: no

...