---

- name: Destroy an instance
  scaleway_compute:
    name: minikube-environment
    state: absent
    image: 2e1353f3-02f7-441f-ab68-7218b874e341
    organization: "{{ scaleway_organization_id }}"
    region: par1
    commercial_type: DEV1-S
    wait: true
...