---

- name: Destroy an instance
  scaleway_compute:
    name: "{{ vm.name }}"
    state: absent
    image: "{{ vm.image_os }}"
    organization: "{{ scaleway_organization_id }}"
    region: "{{ vm.region }}"
    commercial_type: "{{ vm.commercial_type }}"
    wait: true
  loop: "{{ vm_configuration }}"
  loop_control:
    loop_var: vm

...