---

- name: Ensure minikube in {{ minikube_version }} version is installed.
  get_url:
    url: https://storage.googleapis.com/minikube/releases/{{ minikube_version }}/minikube-linux-amd64
    dest: ./minikube
  register: download_result

- name: Ensure minikube is executable.
  file:
    path: ./minikube
    owner: root
    group: root
    mode: '0755'
  when: download_result.status_code == 200

- name: Move minikube binary.
  command: sudo mv minikube /usr/local/bin
  when: download_result.status_code == 200

...