---

- name: Create an instance.
  scaleway_compute:
    name: "{{ vm.name }}"
    state: running
    image: "{{ vm.image_os }}"
    organization: "{{ scaleway_organization_id }}"
    region: "{{ vm.region }}"
    commercial_type: "{{ vm.commercial_type }}"
    public_ip: "{{ vm.public_ip}}"
    tags: ["{{ vm.tag }}"]
    wait: true
  loop: "{{ vm_configuration }}"
  loop_control:
    loop_var: vm

...
